pipeline:
  build:
    image: node:9.6.0
    commands:
      - npm install
      - npm run build
    when:
      event: tag

  npm:
    image: plugins/npm
    secrets: [ npm_password ]
    username: sulliwane
    email: sulliwane@gmail.com
    when:
      event: tag
